# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BankAssignmentMatrix.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BankAssignmentMatrix(object):
    def setupUi(self, BankAssignmentMatrix):
        BankAssignmentMatrix.setObjectName("BankAssignmentMatrix")
        BankAssignmentMatrix.resize(392, 292)
        self.verticalLayout = QtWidgets.QVBoxLayout(BankAssignmentMatrix)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAddRow = QtWidgets.QPushButton(BankAssignmentMatrix)
        self.btnAddRow.setObjectName("btnAddRow")
        self.horizontalLayout.addWidget(self.btnAddRow)
        self.btnRemoveRow = QtWidgets.QPushButton(BankAssignmentMatrix)
        self.btnRemoveRow.setObjectName("btnRemoveRow")
        self.horizontalLayout.addWidget(self.btnRemoveRow)
        self.btnAddColumn = QtWidgets.QPushButton(BankAssignmentMatrix)
        self.btnAddColumn.setObjectName("btnAddColumn")
        self.horizontalLayout.addWidget(self.btnAddColumn)
        self.btnRemoveColumn = QtWidgets.QPushButton(BankAssignmentMatrix)
        self.btnRemoveColumn.setObjectName("btnRemoveColumn")
        self.horizontalLayout.addWidget(self.btnRemoveColumn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tblMatrix = QtWidgets.QTableWidget(BankAssignmentMatrix)
        self.tblMatrix.setObjectName("tblMatrix")
        self.tblMatrix.setColumnCount(3)
        self.tblMatrix.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tblMatrix.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMatrix.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMatrix.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMatrix.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMatrix.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMatrix.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMatrix.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblMatrix.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tblMatrix)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnCreateBanks = QtWidgets.QPushButton(BankAssignmentMatrix)
        self.btnCreateBanks.setObjectName("btnCreateBanks")
        self.horizontalLayout_2.addWidget(self.btnCreateBanks)
        self.btnAssignMedia = QtWidgets.QPushButton(BankAssignmentMatrix)
        self.btnAssignMedia.setObjectName("btnAssignMedia")
        self.horizontalLayout_2.addWidget(self.btnAssignMedia)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(BankAssignmentMatrix)
        QtCore.QMetaObject.connectSlotsByName(BankAssignmentMatrix)

    def retranslateUi(self, BankAssignmentMatrix):
        _translate = QtCore.QCoreApplication.translate
        BankAssignmentMatrix.setWindowTitle(_translate("BankAssignmentMatrix", "Bank Assignment Matrix"))
        self.btnAddRow.setText(_translate("BankAssignmentMatrix", "Add Row"))
        self.btnRemoveRow.setText(_translate("BankAssignmentMatrix", "Remove Row"))
        self.btnAddColumn.setText(_translate("BankAssignmentMatrix", "Add Column"))
        self.btnRemoveColumn.setText(_translate("BankAssignmentMatrix", "Remove Column"))
        item = self.tblMatrix.verticalHeaderItem(0)
        item.setText(_translate("BankAssignmentMatrix", "1"))
        item = self.tblMatrix.verticalHeaderItem(1)
        item.setText(_translate("BankAssignmentMatrix", "2"))
        item = self.tblMatrix.verticalHeaderItem(2)
        item.setText(_translate("BankAssignmentMatrix", "3"))
        item = self.tblMatrix.verticalHeaderItem(3)
        item.setText(_translate("BankAssignmentMatrix", "4"))
        item = self.tblMatrix.verticalHeaderItem(4)
        item.setText(_translate("BankAssignmentMatrix", "5"))
        item = self.tblMatrix.horizontalHeaderItem(0)
        item.setText(_translate("BankAssignmentMatrix", "1"))
        item = self.tblMatrix.horizontalHeaderItem(1)
        item.setText(_translate("BankAssignmentMatrix", "2"))
        item = self.tblMatrix.horizontalHeaderItem(2)
        item.setText(_translate("BankAssignmentMatrix", "3"))
        self.btnCreateBanks.setText(_translate("BankAssignmentMatrix", "Create Banks"))
        self.btnAssignMedia.setText(_translate("BankAssignmentMatrix", "Assign Media"))
