# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 690)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblSourceProject = QtWidgets.QLabel(self.centralwidget)
        self.lblSourceProject.setObjectName("lblSourceProject")
        self.horizontalLayout.addWidget(self.lblSourceProject)
        self.cbbSourceProject = QtWidgets.QComboBox(self.centralwidget)
        self.cbbSourceProject.setObjectName("cbbSourceProject")
        self.horizontalLayout.addWidget(self.cbbSourceProject)
        self.lblTargetProject = QtWidgets.QLabel(self.centralwidget)
        self.lblTargetProject.setObjectName("lblTargetProject")
        self.horizontalLayout.addWidget(self.lblTargetProject)
        self.cbbTargetProject = QtWidgets.QComboBox(self.centralwidget)
        self.cbbTargetProject.setObjectName("cbbTargetProject")
        self.horizontalLayout.addWidget(self.cbbTargetProject)
        self.btnSearchForDifference = QtWidgets.QPushButton(self.centralwidget)
        self.btnSearchForDifference.setObjectName("btnSearchForDifference")
        self.horizontalLayout.addWidget(self.btnSearchForDifference)
        self.btnMoveAllToTarget = QtWidgets.QPushButton(self.centralwidget)
        self.btnMoveAllToTarget.setObjectName("btnMoveAllToTarget")
        self.horizontalLayout.addWidget(self.btnMoveAllToTarget)
        self.cbxSelectAll = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxSelectAll.setChecked(True)
        self.cbxSelectAll.setObjectName("cbxSelectAll")
        self.horizontalLayout.addWidget(self.cbxSelectAll)
        self.cbxNewerFiles = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxNewerFiles.setChecked(True)
        self.cbxNewerFiles.setObjectName("cbxNewerFiles")
        self.horizontalLayout.addWidget(self.cbxNewerFiles)
        self.cbxLargerFiles = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxLargerFiles.setChecked(True)
        self.cbxLargerFiles.setObjectName("cbxLargerFiles")
        self.horizontalLayout.addWidget(self.cbxLargerFiles)
        self.cbxNewFiles = QtWidgets.QCheckBox(self.centralwidget)
        self.cbxNewFiles.setChecked(True)
        self.cbxNewFiles.setObjectName("cbxNewFiles")
        self.horizontalLayout.addWidget(self.cbxNewFiles)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tblFileList = QtWidgets.QTableWidget(self.centralwidget)
        self.tblFileList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblFileList.setObjectName("tblFileList")
        self.tblFileList.setColumnCount(5)
        self.tblFileList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tblFileList)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wwise集成代码同步工具"))
        self.lblSourceProject.setText(_translate("MainWindow", "源项目"))
        self.lblTargetProject.setText(_translate("MainWindow", "目标项目"))
        self.btnSearchForDifference.setText(_translate("MainWindow", "比对代码差异"))
        self.btnMoveAllToTarget.setText(_translate("MainWindow", "移动选中文件到新工程"))
        self.cbxSelectAll.setText(_translate("MainWindow", "全选"))
        self.cbxNewerFiles.setText(_translate("MainWindow", "更新"))
        self.cbxLargerFiles.setText(_translate("MainWindow", "更大"))
        self.cbxNewFiles.setText(_translate("MainWindow", "新增"))
        self.tblFileList.setSortingEnabled(True)
        item = self.tblFileList.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "选中"))
        item = self.tblFileList.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.tblFileList.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "文件大小差异"))
        item = self.tblFileList.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "源文件修改日期"))
        item = self.tblFileList.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "目标文件修改日期"))
