# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AudioTailTrimmer.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AudioTailTrimmer(object):
    def setupUi(self, AudioTailTrimmer):
        AudioTailTrimmer.setObjectName("AudioTailTrimmer")
        AudioTailTrimmer.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(AudioTailTrimmer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnImportFiles = QtWidgets.QPushButton(self.centralwidget)
        self.btnImportFiles.setObjectName("btnImportFiles")
        self.horizontalLayout.addWidget(self.btnImportFiles)
        self.btnAnalyzeTails = QtWidgets.QPushButton(self.centralwidget)
        self.btnAnalyzeTails.setObjectName("btnAnalyzeTails")
        self.horizontalLayout.addWidget(self.btnAnalyzeTails)
        self.btnStartTrim = QtWidgets.QPushButton(self.centralwidget)
        self.btnStartTrim.setObjectName("btnStartTrim")
        self.horizontalLayout.addWidget(self.btnStartTrim)
        self.lblCutThreshold = QtWidgets.QLabel(self.centralwidget)
        self.lblCutThreshold.setObjectName("lblCutThreshold")
        self.horizontalLayout.addWidget(self.lblCutThreshold)
        self.spbCutThreshold = QtWidgets.QSpinBox(self.centralwidget)
        self.spbCutThreshold.setMinimum(-96)
        self.spbCutThreshold.setMaximum(0)
        self.spbCutThreshold.setProperty("value", -48)
        self.spbCutThreshold.setObjectName("spbCutThreshold")
        self.horizontalLayout.addWidget(self.spbCutThreshold)
        self.lblFadeDuration = QtWidgets.QLabel(self.centralwidget)
        self.lblFadeDuration.setObjectName("lblFadeDuration")
        self.horizontalLayout.addWidget(self.lblFadeDuration)
        self.spbFadeDuration = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.spbFadeDuration.setMinimum(0.01)
        self.spbFadeDuration.setMaximum(1.0)
        self.spbFadeDuration.setSingleStep(0.01)
        self.spbFadeDuration.setProperty("value", 0.2)
        self.spbFadeDuration.setObjectName("spbFadeDuration")
        self.horizontalLayout.addWidget(self.spbFadeDuration)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tblFileList = QtWidgets.QTableWidget(self.centralwidget)
        self.tblFileList.setDragEnabled(True)
        self.tblFileList.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tblFileList.setObjectName("tblFileList")
        self.tblFileList.setColumnCount(4)
        self.tblFileList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tblFileList)
        AudioTailTrimmer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AudioTailTrimmer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        AudioTailTrimmer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AudioTailTrimmer)
        self.statusbar.setObjectName("statusbar")
        AudioTailTrimmer.setStatusBar(self.statusbar)

        self.retranslateUi(AudioTailTrimmer)
        QtCore.QMetaObject.connectSlotsByName(AudioTailTrimmer)

    def retranslateUi(self, AudioTailTrimmer):
        _translate = QtCore.QCoreApplication.translate
        AudioTailTrimmer.setWindowTitle(_translate("AudioTailTrimmer", "Audio Tail Trimmer - made by feizhuliu"))
        self.btnImportFiles.setText(_translate("AudioTailTrimmer", "Import Audio Files"))
        self.btnAnalyzeTails.setText(_translate("AudioTailTrimmer", "Analyze Tails"))
        self.btnStartTrim.setText(_translate("AudioTailTrimmer", "Start Trimming"))
        self.lblCutThreshold.setText(_translate("AudioTailTrimmer", "Trim Volume Threshold"))
        self.spbCutThreshold.setSuffix(_translate("AudioTailTrimmer", "dB"))
        self.lblFadeDuration.setText(_translate("AudioTailTrimmer", "Fade out Duration"))
        self.spbFadeDuration.setSuffix(_translate("AudioTailTrimmer", "s"))
        item = self.tblFileList.horizontalHeaderItem(0)
        item.setText(_translate("AudioTailTrimmer", "Audio File"))
        item = self.tblFileList.horizontalHeaderItem(1)
        item.setText(_translate("AudioTailTrimmer", "Total Duration"))
        item = self.tblFileList.horizontalHeaderItem(2)
        item.setText(_translate("AudioTailTrimmer", "Tail Duration"))
        item = self.tblFileList.horizontalHeaderItem(3)
        item.setText(_translate("AudioTailTrimmer", "Status"))
