# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatchReplaceTool.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BatchReplaceTool(object):
    def setupUi(self, BatchReplaceTool):
        BatchReplaceTool.setObjectName("BatchReplaceTool")
        BatchReplaceTool.resize(251, 143)
        self.verticalLayout = QtWidgets.QVBoxLayout(BatchReplaceTool)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFindText = QtWidgets.QLabel(BatchReplaceTool)
        self.lblFindText.setMinimumSize(QtCore.QSize(75, 0))
        self.lblFindText.setObjectName("lblFindText")
        self.horizontalLayout.addWidget(self.lblFindText)
        self.iptFindName = QtWidgets.QLineEdit(BatchReplaceTool)
        self.iptFindName.setObjectName("iptFindName")
        self.horizontalLayout.addWidget(self.iptFindName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblReplaceText = QtWidgets.QLabel(BatchReplaceTool)
        self.lblReplaceText.setMinimumSize(QtCore.QSize(75, 0))
        self.lblReplaceText.setObjectName("lblReplaceText")
        self.horizontalLayout_2.addWidget(self.lblReplaceText)
        self.iptReplaceName = QtWidgets.QLineEdit(BatchReplaceTool)
        self.iptReplaceName.setObjectName("iptReplaceName")
        self.horizontalLayout_2.addWidget(self.iptReplaceName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblObjectType = QtWidgets.QLabel(BatchReplaceTool)
        self.lblObjectType.setMinimumSize(QtCore.QSize(75, 0))
        self.lblObjectType.setObjectName("lblObjectType")
        self.horizontalLayout_3.addWidget(self.lblObjectType)
        self.cbxObjectType = QtWidgets.QComboBox(BatchReplaceTool)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxObjectType.sizePolicy().hasHeightForWidth())
        self.cbxObjectType.setSizePolicy(sizePolicy)
        self.cbxObjectType.setObjectName("cbxObjectType")
        self.horizontalLayout_3.addWidget(self.cbxObjectType)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.btnDoReplace = QtWidgets.QPushButton(BatchReplaceTool)
        self.btnDoReplace.setObjectName("btnDoReplace")
        self.verticalLayout.addWidget(self.btnDoReplace)

        self.retranslateUi(BatchReplaceTool)
        QtCore.QMetaObject.connectSlotsByName(BatchReplaceTool)

    def retranslateUi(self, BatchReplaceTool):
        _translate = QtCore.QCoreApplication.translate
        BatchReplaceTool.setWindowTitle(_translate("BatchReplaceTool", "模板复制替换工具"))
        self.lblFindText.setText(_translate("BatchReplaceTool", "查找字段"))
        self.lblReplaceText.setText(_translate("BatchReplaceTool", "替换成"))
        self.lblObjectType.setText(_translate("BatchReplaceTool", "替换对象类型"))
        self.btnDoReplace.setText(_translate("BatchReplaceTool", "进行查找替换"))
