# Form implementation generated from reading ui file 'RenameByTable.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RenameByTable(object):
    def setupUi(self, RenameByTable):
        RenameByTable.setObjectName("RenameByTable")
        RenameByTable.resize(372, 630)
        self.verticalLayout = QtWidgets.QVBoxLayout(RenameByTable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnChooseConfig = QtWidgets.QPushButton(parent=RenameByTable)
        self.btnChooseConfig.setObjectName("btnChooseConfig")
        self.horizontalLayout.addWidget(self.btnChooseConfig)
        self.cbxHasHeaderRow = QtWidgets.QCheckBox(parent=RenameByTable)
        self.cbxHasHeaderRow.setChecked(True)
        self.cbxHasHeaderRow.setObjectName("cbxHasHeaderRow")
        self.horizontalLayout.addWidget(self.cbxHasHeaderRow)
        self.btnDoRename = QtWidgets.QPushButton(parent=RenameByTable)
        self.btnDoRename.setObjectName("btnDoRename")
        self.horizontalLayout.addWidget(self.btnDoRename)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbxPlayPrefix = QtWidgets.QCheckBox(parent=RenameByTable)
        self.cbxPlayPrefix.setChecked(True)
        self.cbxPlayPrefix.setObjectName("cbxPlayPrefix")
        self.horizontalLayout_2.addWidget(self.cbxPlayPrefix)
        self.cbxHasRoleSuffix = QtWidgets.QCheckBox(parent=RenameByTable)
        self.cbxHasRoleSuffix.setChecked(True)
        self.cbxHasRoleSuffix.setObjectName("cbxHasRoleSuffix")
        self.horizontalLayout_2.addWidget(self.cbxHasRoleSuffix)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tblConfigItems = QtWidgets.QTableWidget(parent=RenameByTable)
        self.tblConfigItems.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tblConfigItems.setObjectName("tblConfigItems")
        self.tblConfigItems.setColumnCount(3)
        self.tblConfigItems.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblConfigItems.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConfigItems.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblConfigItems.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tblConfigItems)

        self.retranslateUi(RenameByTable)
        QtCore.QMetaObject.connectSlotsByName(RenameByTable)

    def retranslateUi(self, RenameByTable):
        _translate = QtCore.QCoreApplication.translate
        RenameByTable.setWindowTitle(_translate("RenameByTable", "读表批量重命名"))
        self.btnChooseConfig.setText(_translate("RenameByTable", "选择CSV文件"))
        self.cbxHasHeaderRow.setText(_translate("RenameByTable", "CSV带有表头行"))
        self.btnDoRename.setText(_translate("RenameByTable", "进行重命名"))
        self.cbxPlayPrefix.setText(_translate("RenameByTable", "Event带有Play_前缀"))
        self.cbxHasRoleSuffix.setText(_translate("RenameByTable", "Event带有1P/3P后缀"))
        item = self.tblConfigItems.horizontalHeaderItem(0)
        item.setText(_translate("RenameByTable", "原命名"))
        item = self.tblConfigItems.horizontalHeaderItem(1)
        item.setText(_translate("RenameByTable", "新命名"))
        item = self.tblConfigItems.horizontalHeaderItem(2)
        item.setText(_translate("RenameByTable", "当前配置"))
