# Form implementation generated from reading ui file 'ReplaceByTemplate.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ReplaceByTemplate(object):
    def setupUi(self, ReplaceByTemplate):
        ReplaceByTemplate.setObjectName("ReplaceByTemplate")
        ReplaceByTemplate.resize(251, 143)
        self.verticalLayout = QtWidgets.QVBoxLayout(ReplaceByTemplate)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFindText = QtWidgets.QLabel(parent=ReplaceByTemplate)
        self.lblFindText.setMinimumSize(QtCore.QSize(75, 0))
        self.lblFindText.setObjectName("lblFindText")
        self.horizontalLayout.addWidget(self.lblFindText)
        self.iptFindName = QtWidgets.QLineEdit(parent=ReplaceByTemplate)
        self.iptFindName.setObjectName("iptFindName")
        self.horizontalLayout.addWidget(self.iptFindName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblReplaceText = QtWidgets.QLabel(parent=ReplaceByTemplate)
        self.lblReplaceText.setMinimumSize(QtCore.QSize(75, 0))
        self.lblReplaceText.setObjectName("lblReplaceText")
        self.horizontalLayout_2.addWidget(self.lblReplaceText)
        self.iptReplaceName = QtWidgets.QLineEdit(parent=ReplaceByTemplate)
        self.iptReplaceName.setObjectName("iptReplaceName")
        self.horizontalLayout_2.addWidget(self.iptReplaceName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblObjectType = QtWidgets.QLabel(parent=ReplaceByTemplate)
        self.lblObjectType.setMinimumSize(QtCore.QSize(75, 0))
        self.lblObjectType.setObjectName("lblObjectType")
        self.horizontalLayout_3.addWidget(self.lblObjectType)
        self.cbxObjectType = QtWidgets.QComboBox(parent=ReplaceByTemplate)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxObjectType.sizePolicy().hasHeightForWidth())
        self.cbxObjectType.setSizePolicy(sizePolicy)
        self.cbxObjectType.setObjectName("cbxObjectType")
        self.horizontalLayout_3.addWidget(self.cbxObjectType)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.btnDoReplace = QtWidgets.QPushButton(parent=ReplaceByTemplate)
        self.btnDoReplace.setObjectName("btnDoReplace")
        self.verticalLayout.addWidget(self.btnDoReplace)

        self.retranslateUi(ReplaceByTemplate)
        QtCore.QMetaObject.connectSlotsByName(ReplaceByTemplate)

    def retranslateUi(self, ReplaceByTemplate):
        _translate = QtCore.QCoreApplication.translate
        ReplaceByTemplate.setWindowTitle(_translate("ReplaceByTemplate", "模板批量替换"))
        self.lblFindText.setText(_translate("ReplaceByTemplate", "查找字段"))
        self.lblReplaceText.setText(_translate("ReplaceByTemplate", "替换成"))
        self.lblObjectType.setText(_translate("ReplaceByTemplate", "替换对象类型"))
        self.btnDoReplace.setText(_translate("ReplaceByTemplate", "进行查找替换"))
