# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UnityResourceManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UnityResourceManager(object):
    def setupUi(self, UnityResourceManager):
        UnityResourceManager.setObjectName("UnityResourceManager")
        UnityResourceManager.resize(548, 574)
        self.verticalLayout = QtWidgets.QVBoxLayout(UnityResourceManager)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSelectResourceFolder = QtWidgets.QPushButton(UnityResourceManager)
        self.btnSelectResourceFolder.setObjectName("btnSelectResourceFolder")
        self.horizontalLayout.addWidget(self.btnSelectResourceFolder)
        self.btnDeleteSelected = QtWidgets.QPushButton(UnityResourceManager)
        self.btnDeleteSelected.setObjectName("btnDeleteSelected")
        self.horizontalLayout.addWidget(self.btnDeleteSelected)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tblFileList = QtWidgets.QTableWidget(UnityResourceManager)
        self.tblFileList.setDragEnabled(True)
        self.tblFileList.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.tblFileList.setObjectName("tblFileList")
        self.tblFileList.setColumnCount(4)
        self.tblFileList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblFileList.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tblFileList)

        self.retranslateUi(UnityResourceManager)
        QtCore.QMetaObject.connectSlotsByName(UnityResourceManager)

    def retranslateUi(self, UnityResourceManager):
        _translate = QtCore.QCoreApplication.translate
        UnityResourceManager.setWindowTitle(_translate("UnityResourceManager", " Unity Resource管理"))
        self.btnSelectResourceFolder.setText(_translate("UnityResourceManager", "选择Resource文件夹"))
        self.btnDeleteSelected.setText(_translate("UnityResourceManager", "删除选中资源"))
        self.tblFileList.setSortingEnabled(True)
        item = self.tblFileList.horizontalHeaderItem(0)
        item.setText(_translate("UnityResourceManager", "名称"))
        item = self.tblFileList.horizontalHeaderItem(1)
        item.setText(_translate("UnityResourceManager", "类型"))
        item = self.tblFileList.horizontalHeaderItem(2)
        item.setText(_translate("UnityResourceManager", "状态"))
        item = self.tblFileList.horizontalHeaderItem(3)
        item.setText(_translate("UnityResourceManager", "GUID"))
